 #!/bin/bash

 n=$((( RANDOM % 113 ) + 1))

case $n in
    1) echo "Go!";;
    2) echo "Don't tell people your plans. Show them your results.";;
    3) echo "No pressure, no diamonds.";;
    4) echo "We can do anything we want to if we stick to it long enough.";;
    5) echo "Stay foolish to stay sane.";;
    6) echo "When nothing goes right, go left.";;
    7) echo "Try Again. Fail again. Fail better.";;
    8) echo "Impossible is for the unwilling.";;
    9) echo "Once you choose hope, anything's possible. ";;
    10) echo "I can and I will.";;
    11) echo "Take the risk or lose the chance.";;
    12) echo "Good things happen to those who hustle.";;
    13) echo "Solitary trees, if they grow at all, grow strong.";;
    14) echo "Go forth on your path, as it exists only through your walking.";;
    15) echo "He who is brave is free.";;
    16) echo "Prove them wrong.";;
    17) echo "The question is not what you look at, but what you see.";;
    18) echo "Screw it, let's do it.";;
    19) echo "Boldness be my friend.";;
    20) echo "Keep going. Be all in.";;
    21) echo "If you want it, work for it.";;
    22) echo "You can if you think you can.";;
    23) echo "Whatever you are, be a good one.";;
    24) echo "Grow through what you go through.";;
    25) echo "Do it with passion or not at all.";;
    26) echo "If it matters to you, you'll find a way.";;
    27) echo "The past does not equal the future.";;
    28) echo "Dream without fear. love without limits.";;
    29) echo "It is not the mountain we conquer but ourselves.";;
    30) echo "Whatever you do, do with all your might.";;
    31) echo "Every noble work is at first impossible.";;
    32) echo "If you’re going through hell, keep going.";;
    33) echo "Be faithful to that which exists within yourself.";;
    34) echo "Persistence guarantees that results are inevitable.";;
    35) echo "When one door of happiness closes, another opens.";;
    36) echo "Mastering others is strength. Mastering yourself is true power.";;
    37) echo "The true success is the person who invented himself.";;
    38) echo "Fall seven times, stand up eight.";;
    39) echo "You can totally do this!";;
    40) echo "Never stop dreaming.";;
    41) echo "Now is all you have.";;
    42) echo "Pain is temporary. Quitting lasts forever.";;
    43) echo "Stars can’t shine without darkness.";;
    44) echo "Be who you needed when you were young.";;
    45) echo "Don’t let yesterday take up too much of today.";;
    46) echo "The truth isn’t always beauty, but the hunger for it is. ";;
    47) echo "Stay close to anything that makes you glad you are alive.";;
    48) echo "Happiness is not by chance, but by choice.";;
    49) echo "It is never too late to be what you might have been.";;
    50) echo "No matter what you’re going through, there’s a light at the end of the tunnel.";;
    51) echo "It isn’t where you came from. It’s where you’re going that counts.";;
    52) echo "Yesterday is done. Tomorrow never comes. Today is here.";;
    53) echo "When you have a dream, you’ve got to grab it and never let go.";;
    54) echo "You must do the things you think you cannot do.";;
    55) echo "To be the best, you must be able to handle the worst.";;
    56) echo "Life isn’t about finding yourself. Life is about creating yourself.";;
    57) echo "Always do what you are afraid to do.";;
    58) echo "If you can dream it, you can do it.";;
    59) echo "Defeat may serve as well as victory to shake the soul and let the glory out.";;
    60) echo "Rise above the storm and you will find the sunshine.";;
    61) echo "Begin anywhere.";;
    62) echo "Have faith in yourself and in the future.";;
    63) echo "Do it Now!";;
    64) echo "The best way to prepare for life is to begin to live.";;
    65) echo "No great thing is created suddenly.";;
    66) echo "It’s not the years in your life that count. It is the life in your years.";;
    67) echo "To know oneself, one should assert oneself.";;
    68) echo "There is no substitute for hard work.";;
    69) echo "Luck is a matter of preparation meeting opportunity.";;
    70) echo "Do what you can, with what you have, where you are.";;
    71) echo "Don’t worry about the challenges. Get excited about the rewards of crushing them.";;
    72) echo "Keep going. Is not as difficult as you feel it is. Don’t give up.";;
    73) echo "I may stumble. I may fall. I may cry. But I’ll NEVER give up! Tomorrow, I rise again.";;
    74) echo "Dream big, stay positive, work hard, and enjoy the journey.";;
    75) echo "Nothing is impossible to a willing heart.";;
    76) echo "Pain is inevitable. Suffering is optional.";;
    77) echo "Never regret anything that made you smile.";;
    78) echo "Aim for the moon. If you miss, you may hit a star.";;
    79) echo "Ninety-nine percent of the failures come from people who have the habit of making excuses.";;
    80) echo "In the middle of difficulty lies opportunity.";;
    81) echo "He that can have patience can have what he will.";;
    82) echo "Success is not final, failure is not fatal: it is the courage to continue that counts.";;
    83) echo "It is during our darkest moments that we must focus to see the light.";;
    84) echo "If you want to see a rainbow you have to learn to see the rain.";;
    85) echo "I’m a slow walker, but I never walk back.";;
    86) echo "Learn as if you will live forever, live like you will die tomorrow.";;
    87) echo "If your dreams don’t scare you, they are too small.";;
    88) echo "It is better to fail in originality than to succeed in imitation.";;
    89) echo "Either you run the time or the time runs you.";;
    90) echo "We will either find a way, or make one.";;
    91) echo "Don’t wish it were easier. Wish you were better.";;
    92) echo "The best way out is always through.";;
    93) echo "Do the hard jobs first. The easy jobs will take care of themselves.";;
    94) echo "It’s kind of fun to do the impossible.";;
    95) echo "To think too long about doing a thing often becomes its undoing.";;
    96) echo "Too many of us are not living our dreams because we are living our fears.";;
    97) echo "No one really knows why they are alive until they know what they’d die for.";;
    98) echo "Follow your dreams, they know the way.";;
    99) echo "There is only one thing that makes a dream impossible to achieve: the fear of failure.";;
    100) echo "There is no elevator to success. You have to take the stairs.";;
    101) echo "Success usually comes to those who are too busy looking for it.";;
    102) echo "Skill is only developed by hours and hours of work.";;
    103) echo "The beautiful thing about learning is that nobody can take it away from you.";;
    104) echo "If you have no confidence in self, you are twice defeated in the race of life.";;
    105) echo "Just one small positive thought in the morning can change your whole day.";;
    106) echo "Procrastination makes easy things hard and hard things harder.";;
    107) echo "Motivation is what gets you started. Habit is what keeps you going.";;
    108) echo "It always seems impossible until it’s done.";;
    109) echo "Quietly endure, silently suffer and patiently wait.";;
    110) echo "Life’s struggles are necessary for growth.";;
    111) echo "Our greatest glory is not in never falling, but in rising every time we fall.";;
    112) echo "No pains, no gains.";;
    *) echo "Happy Day!"
esac

